name: Build Binaries
# Hellow world

on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag name'
                required: true
    push:
        branches:
            - main

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11
            - name: Install requirements
              run: |
                  pip install -r  buildReq.txt
            - name: Build
              run: |
                  pyinstaller -F -y __main__.py
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: dist
    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: build
            - name: Rename __main__ to release-osx so it is better
              run: |
                  mv build/__main__ build/release-osx
            # if manual dispatch is used, use an argument as tag name, else use ref
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: build/release-osx
                  prerelease: true
                  generate_release_notes: true
                  tag_name: ${{ github.event.inputs.tag || github.workflow_sha }}