name: "Debug Build"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11
            - name: Build
              run: |
                  python3 __main__.py --debug
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: source-engine/hl2